# Generated by Django 5.1.4 on 2024-12-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Priority', models.CharField(max_length=50)),
                ('Creation_Date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
