# Generated by Django 5.1.4 on 2024-12-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createnew',
            name='Deadline',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
