# Generated by Django 5.1.4 on 2024-12-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_todo_delete_createnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Deadline',
            field=models.DateField(),
        ),
    ]
