# Generated by Django 5.1.4 on 2024-12-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0005_remove_todo_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='High', max_length=10),
        ),
    ]
