# Generated by Django 5.1.4 on 2024-12-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0006_alter_todo_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
