# Generated by Django 5.1.4 on 2024-12-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0007_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Creation_Date',
            field=models.DateField(auto_now=True),
        ),
    ]
